name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt update
          sudo apt install -y clang-format-21 clang-tidy-21 just cmake

          sudo ln -sf /usr/bin/clang-format-21 /usr/bin/clang-format
          sudo ln -sf /usr/bin/clang-tidy-21 /usr/bin/clang-tidy

      - name: Generate compile_commands.json
        run: |
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-format
        run: |
          just check-format

      - name: Run clang-tidy
        run: |
          just tidy
